baseURL = "https://98k.pages.dev" 
defaultContentLanguage = "zh" 
disqusShortname = "" # your discuss shortname         # Disqus评论系统代码
enableEmoji = true 
googleAnalytics = "" # your google analytics id       # Google统计代码
hasCJKLanguage = true # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
languageCode = "zh" 
paginate = 4 # shows the number of articles   # 首页显示文章数量
summaryLength = 100 
theme = "zozo" 
title = "98K" # site title                     # 网站标题

pygmentCodeFences = true
pygmentsUseClasses = true
pygmentscodefencesguesssyntax = true

[author] # essential                      # 必需
name = "98k"

[blackfriday]
smartypants = false

[[menu.main]] # config your menu               # 配置菜单
identifier = "home"
name = "Home"
url = "/"
weight = 10
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/posts/"
weight = 20
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 40

[params]
description = "98K is a blog that shares programming software." # site's description           # 网站描述
enableMathJax = true # enable mathjax               # 是否使用mathjax（数学公式）
enableSummary = true # display the article summary  # 是否显示文章摘要
footerSlogan = "Happiness and freedom." # site's footer slogan         # 网站页脚标语
keywords = ["Hugo", "theme", "zozo", "chatgpt", "openai"] # site's keywords              # 网站关键字            
mainSections = ["posts", "post"] 
subTitle = "98K" # site's subTitle              # 网站二级标题

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
appId = ""
appKey = ""
enable = false
placeholder = " "
visitor = true

# Your socail's url
# 社交地址配置
[social]
facebook = " "
github = " "
instagram = " "
twitter = " "
weibo = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
